= %placeholder% blog

This is where we're going to write down what we've done so far.

== Entries

* 8.09.2022 - *Timo:* Creating the blog file, writing code to read response from mainboard and adding `robot.py` to GitHub. (2h)
* 11.09.2022 - *Artur:* Assembling the test robot mechanics. (4h)
* 12.09.2022 - *Timo:* Updating `robot.py` to switch to `while` loop, testing wheel moving. (3h)
* 12.09.2022 - *Jens:* Debugging, helping with electronics. Found out why one of the motors didn't work - bolts were too long. (3h)
* 13.09.2022 - *Artur:* Drilled a big hole for cable management. (1h)
* 15.09.2022 - *Artur:* Debugged why one motor was not driving backwards. (1.5h)
* 19.09.2022 - *Artur:* Finished debugging, turns out some isolation scraped off and it was getting shorted out in the backwards direction. (2.5h)
* 19.09.2022 - *Timo:* Presented the project. (2h)
* 22.09.2022 - *Artur:* Debugged thrower problems, turns out mainboard voltage regulator was broken, so no signal passed from the isolator to the thrower. (4h)
* 22.09.2022 - *Timo:* Testing different remote control solutions to find the best one for our use case. (2h)
* 26.09.2022 - *Artur:* Redid the robot wiring to fit the batteries better, and got the battery training. (2.5h)
* 26.09.2022 - *Timo:* SSH setup, to control the computer remotely. (2h)
* 03.10.2022 - *Timo:* Testing robot, doing the presentation. (2h)
* 03.10.2022 - *Artur:* Testing robot, doing the presentation, debugging. (2h)
* 06.10.2022 - *Timo:* More SSH setup, can now see camera via SSH. Screwed in some bolts so the robot wouldn't fall apart (2h)
* 13.10.2022 - *Timo:* Movement code, DualShock 4 support (6h)
* 14.10.2022 - *Timo:* Debugging movement, looking into camera code. (1.5h)
