= %placeholder% blog

This is where we're going to write down what we've done so far.

== Entries

* 8.09.2022 - *Timo:* Creating the blog file, writing code to read response from mainboard and adding `robot.py` to GitHub. (2h)
* 11.09.2022 - *Artur:* Assembling the test robot mechanics. (4h)
* 12.09.2022 - *Timo:* Updating `robot.py` to switch to `while` loop, testing wheel moving. (3h)
* 12.09.2022 - *Jens:* Debugging, helping with electronics. Found out why one of the motors didn't work - bolts were too long. (3h)
* 13.09.2022 - *Artur:* Drilled a big hole for cable management. (1h)
* 15.09.2022 - *Artur:* Debugged why one motor was not driving backwards. (1.5h)
* 19.09.2022 - *Artur:* Finished debugging, turns out some isolation scraped off and it was getting shorted out in the backwards direction. (2.5h)
* 19.09.2022 - *Timo:* Presented the project. (2h)
* 22.09.2022 - *Artur:* Debugged thrower problems, turns out mainboard voltage regulator was broken, so no signal passed from the isolator to the thrower. (4h)
* 22.09.2022 - *Timo:* Testing different remote control solutions to find the best one for our use case. (2h)
* 26.09.2022 - *Artur:* Redid the robot wiring to fit the batteries better, and got the battery training. (2.5h)
* 26.09.2022 - *Timo:* SSH setup, to control the computer remotely. (2h)
* 03.10.2022 - *Timo:* Testing robot, doing the presentation. (2h)
* 03.10.2022 - *Artur:* Testing robot, doing the presentation, debugging. (2h)
* 06.10.2022 - *Timo:* More SSH setup, can now see camera via SSH. Screwed in some bolts so the robot wouldn't fall apart (2h)
* 13.10.2022 - *Timo:* Movement code, DualShock 4 support (6h)
* 14.10.2022 - *Timo:* Debugging movement, looking into camera code. (1.5h)
* 15.10.2022 - *Timo:* Movement testing, rewriting controller code, putting wheels back on the robot. (2.5h)
* 15.10.2022 - *Artur:* Checking robot MAC address, importing libraries, creating missing components, getting familiarised with Altium Designer. (5h)
* 16.10.2022 - *Artur:* Working on the schematic, browsing through datasheets. (4h)
* 16.10.2022 - *Jens:* Started work on thrower. (1.5h)
* 17.10.2022 - *Artur:* Working on the schematic, browsing throught some more datasheets. (3.5h)
* 17.10.2022 - *Jens:* Researched thrower design. (0.5h)
* 17.10.2022 - *Timo:* Fixed one of the wheels falling off. (0.5h)
* 17.10.2022 - *Jens:* Fixed one of the wheels falling off. (0.5h)
* 18.10.2022 - *Timo:* Cleaned up and improved DS4 control code. (1.5h)
* 24.10.2022 - *Timo:* Looking into camera stuff. (1.5h)
* 28.10.2022 - *Jens:* Print out test parts. (3h)
* 30.10.2022 - *Artur:* Fixing schematic issues. (6h)
* 31.10.2022 - *Artur:* Starting with PCB design, debugging library footprint issues. (3h)
* 01.11.2022 - *Timo:* Fixing deadzone issues with DS4 controller. Fixed the basic autonomous code. Added mode switching to controller. Started work on a state machine. (3h)
* 02.11.2022 - *Timo:* State machine fixes. (2h)
* 03.11.2022 - *Jens:* Make millable design (3h)
