= %placeholder% blog

This is where we're going to write down what we've done so far.

Mechanics link: https://a360.co/3SYDOoi

Our team members: Timo Jairus, Artur Salumäe, Jens Olaf Kukk

== Entries

* 8.09.2022 - *Timo:* Creating the blog file, writing code to read response from mainboard and adding `robot.py` to GitHub. (2h)
* 11.09.2022 - *Artur:* Assembling the test robot mechanics. (4h)
* 12.09.2022 - *Timo:* Updating `robot.py` to switch to `while` loop, testing wheel moving. (3h)
* 12.09.2022 - *Jens:* Debugging, helping with electronics. Found out why one of the motors didn't work - bolts were too long. (3h)
* 13.09.2022 - *Artur:* Drilled a big hole for cable management. (1h)
* 15.09.2022 - *Artur:* Debugged why one motor was not driving backwards. (1.5h)
* 19.09.2022 - *Artur:* Finished debugging, turns out some isolation scraped off and it was getting shorted out in the backwards direction. (2.5h)
* 19.09.2022 - *Timo:* Presented the project. (2h)
* 22.09.2022 - *Artur:* Debugged thrower problems, turns out mainboard voltage regulator was broken, so no signal passed from the isolator to the thrower. (4h)
* 22.09.2022 - *Timo:* Testing different remote control solutions to find the best one for our use case. (2h)
* 26.09.2022 - *Artur:* Redid the robot wiring to fit the batteries better, and got the battery training. (2.5h)
* 26.09.2022 - *Timo:* SSH setup, to control the computer remotely. (2h)
* 03.10.2022 - *Timo:* Testing robot, doing the presentation. (2h)
* 03.10.2022 - *Artur:* Testing robot, doing the presentation, debugging. (2h)
* 06.10.2022 - *Timo:* More SSH setup, can now see camera via SSH. Screwed in some bolts so the robot wouldn't fall apart (2h)
* 13.10.2022 - *Timo:* Movement code, DualShock 4 support (6h)
* 14.10.2022 - *Timo:* Debugging movement, looking into camera code. (1.5h)
* 15.10.2022 - *Timo:* Movement testing, rewriting controller code, putting wheels back on the robot. (2.5h)
* 15.10.2022 - *Artur:* Checking robot MAC address, importing libraries, creating missing components, getting familiarised with Altium Designer. (5h)
* 16.10.2022 - *Artur:* Working on the schematic, browsing through datasheets. (4h)
* 16.10.2022 - *Jens:* Started work on thrower. (1.5h)
* 17.10.2022 - *Artur:* Working on the schematic, browsing throught some more datasheets. (3.5h)
* 17.10.2022 - *Jens:* Researched thrower design. (0.5h)
* 17.10.2022 - *Timo:* Fixed one of the wheels falling off. (0.5h)
* 17.10.2022 - *Jens:* Fixed one of the wheels falling off. (0.5h)
* 18.10.2022 - *Timo:* Cleaned up and improved DS4 control code. (1.5h)
* 24.10.2022 - *Timo:* Looking into camera stuff. (1.5h)
* 28.10.2022 - *Jens:* Print out test parts. (3h)
* 30.10.2022 - *Artur:* Fixing schematic issues. (6h)
* 31.10.2022 - *Artur:* Starting with PCB design, debugging library footprint issues + resoldered a lot of the electronics. (8.5h)
* 01.11.2022 - *Timo:* Fixing deadzone issues with DS4 controller. Fixed the basic autonomous code. Added mode switching to controller. Started work on a state machine. (3h)
* 02.11.2022 - *Timo:* State machine fixes. (2h)
* 03.11.2022 - *Jens:* Make millable design (3h)
* 03.11.2022 - *Timo:* Code cleanup and fixes. (6h)
* 03.11.2022 - *Artur:* Resoldered some more stuff, did some PCB design. (4h)
* 04.11.2022 - *Timo:* Documenting functions and removing unused stuff. (1h)
* 05.11.2022 - *Timo:* Working on robot code. (6h)
* 05.11.2022 - *Artur:* Designed PCB, helped with robot software. (9h)
* 06.11.2022 - *Artur:* Helped with robot software. (6h)
* 06.11.2022 - *Timo:* Working on state machine. (6.5h)
* 06.11.2022 - *Jens:* Fix designs (2h)
* 07.11.2022 - *Jens:* Milling and assembling thrower (3h)
* 07.11.2022 - *Timo:* Thrower testing. (2h)
* 08.11.2022 - *Artur:* Redid the PCB, fixed PCB issues, did thrower regression. (8h)
* 08.11.2022 - *Timo:* Thrower testing, gathering data and cleaning up code. (5h)
* 09.11.2022 - *Timo:* Thrower testing, improving robot driving. (4h)
* 09.11.2022 - *Jens:* Fixes (2h)
* 10.11.2022 - *Timo:* Finally getting the robot code in a competitive state, qualifying and taking part of test competition. (10h)
* 10.11.2022 - *Artur:* Helped with software, participated in the test competition. (4h)
* 12.11.2022 - *Artur:* Fixed PCB issues, created PCB issues. (2h)
* 14.11.2022 - *Timo:* Testing referee code. (1h)
* 17.11.2022 - *Timo:* Testing movement, adding in more screws. (2h)
* 18.11.2022 - *Timo:* Improved search function and ball detection. (3h)
* 19.11.2022 - *Timo:* Code cleanup and switching referee code to multiprocessing. (2h)
* 20.11.2022 - *Timo:* More code cleanup and fixes. (1h)
* 21.11.2022 - *Timo:* Programming. (2h)
* 22.11.2022 - *Timo:* More programming. (4h)
* 23.11.2022 - *Timo:* Code cleanup, fixes, fixing mechanical problems, implementing logging. (7h)
* 24.11.2022 - *Timo:* "Improving" code, taking part in test competition. (8h)
* 24.11.2022 - *Artur:* Taking part in test competition. (3h)
* 25.11.2022 - *Jens:* Made new baseplate design, new thrower design, etc (5h)
* 28.11.2022 - *Artur:* Soldering the PCB. (3h)
* 28.11.2022 - *Timo:* Bug fixes, presentation. (5h)
* 01.12.2022 - *Timo:* Code cleanup and fixes, getting code approved. (2h)
* 02.12.2022 - *Timo:* Code cleanup. (2.5h)
* 03.12.2022 - *Timo:* Fixes, code to hopefully save the robot when balls get stuck. (2.5h)
* 04.12.2022 - *Jens:* Mechanics design and fixing issues (5h)
* 04.12.2022 - *Timo:* Programming, fixing basket escape logic. (7h)
* 05.12.2022 - *Timo:* Code adjustment and fixed orbiting with the help of Akustav. (4h)
* 06.12.2022 - *Timo:* Variable adjusting, making use of white pixels in line detection. (3h)
* 07.12.2022 - *Timo:* Calibrated thrower, cleaned the wheels, drilled a hole to attach rear wheel, attempts at improving basket distance detection. (7.5h)
* 08.12.2022 - *Timo:* Adjusted some screws, code cleanup, won the test competition. (5h)
* 09.12.2022 - *Timo:* Minor code cleanup and experimenting with basket color detection. (1h)
* 10.12.2022 - *Jens:* CAM design (2h)
